db_code: pg_archeology_scan # 数据库编号
db_name: 考古扫描数据库 # 数据库名称
db_type: postgresql # 数据库类型
host: 127.0.0.1 # 服务器地址
port: 5432 # 端口号
user: root # 用户名
password: "123321" # 密码
database: archeology_scan # 数据库
